defaults:
  - model: llava-1.5-7b-hf
  - trainer: grad_ascent
  - data: unlearn
  - collator: DataCollatorForSupervisedDataset
  - eval: null
  - hydra: default
  - paths: default
  - experiment: null
  - _self_

trainer:
  args: 
    remove_unused_columns: False

mode: unlearn
task_name: ???